# Generated by Django 4.2 on 2023-05-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/images/")),
                (
                    "thumbnail_200",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/thumbnails_200"
                    ),
                ),
                (
                    "thumbnail_400",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/thumbnails_400"
                    ),
                ),
                ("creation_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
